version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    cap_add:
      - NET_ADMIN
    depends_on:
      db:
        condition: service_healthy
      zcash_zcashd: 
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      RPC_URL: zcash_zcashd
      RPC_USERNAME: user
      RPC_PASSWORD: password
      ALLOW_MULTIPLE_THREADS: true

  db:
    image: postgres:latest
    user: root
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]

  zcash_zcashd:
    image: electriccoinco/zcashd
    user: root
    volumes:
      - ./zcash-data-dir:/srv/zcashd/.zcash
      - ./zcash-params-dir:/srv/zcashd/.zcash-params
      - ./zcash-data-dir/zcash.conf:/root/.zcash/zcash.conf
    environment:
      ZCASHD_NETWORK: "mainnet" 
      ZCASHD_RPCPASSWORD: "password"
      ZCASHD_RPCUSER: "user"
      ZCASHD_ALLOWIP: "0.0.0.0/0"
    ports:
      - "8232:8232"
      - "8233:8233"
    cap_add:
      - NET_ADMIN
    privileged: true

  api:
    user: root
    build:
      context: ../block_explorer_api/  
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"  
    depends_on:
      - db  
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres 
      - DB_USER=postgres 
      - DB_PASSWORD=mysecretpassword
      - PORT=8000

volumes:
  postgres_data:
  zcash_data:
  zcash_params:
