version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: "5432"
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      RPC_URL: host.docker.internal:8232
      RPC_USERNAME: user
      RPC_PASSWORD: ${RPC_PASSWORD}
      BLOCK_CHUNK_PROCESSING_SIZE: ${BLOCK_CHUNK_PROCESSING_SIZE}
      ALLOW_MULTIPLE_THREADS: true

  zcash_zcashd:
    image: electriccoinco/zcashd
    user: "2001:2001" 
    volumes:
      - zcash_data:/srv/zcashd/.zcash
      - zcash_params:/srv/zcashd/.zcash-params
    environment:
      ZCASHD_NETWORK: "testnet" 
      ZCASHD_RPCPASSWORD: ${RPC_PASSWORD}
      ZCASHD_RPCUSER: user
      ZCASHD_ALLOWIP: "0.0.0.0/0"
    ports:
      - "8232:8232"
      - "8233:8233"
      - "18233:18233"
      - "18232:18232"
    cap_add:
      - NET_ADMIN
    privileged: true

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  zcash_data:
  zcash_params:
  postgres_data:
