version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    cap_add:
      - NET_ADMIN
    depends_on:
      zcash_zcashd: 
        condition: service_started
      postgres:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      RPC_URL: zcash_zcashd:8232
      RPC_USERNAME: user
      RPC_PASSWORD: ${RPC_PASSWORD}
      ALLOW_MULTIPLE_THREADS: true

  zcash_zcashd:
    image: electriccoinco/zcashd
    user: "2001:2001" 
    volumes:
      - zcash_data:/srv/zcashd/.zcash
      - zcash_params:/srv/zcashd/.zcash-params
    environment:
      ZCASHD_NETWORK: "mainnet" 
      ZCASHD_RPCPASSWORD: ${ZCASHD_RPCPASSWORD}
      ZCASHD_RPCUSER: "user"
      ZCASHD_ALLOWIP: "0.0.0.0/0"
    ports:
      - "8232:8232"
      - "8233:8233"
    cap_add:
      - NET_ADMIN
    privileged: true

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  zcash_data:
  zcash_params:
  postgres_data:
